### ISSUE TITLE
http/get freezes in d/chain

### ISSUE THREAD

**Issue by shmish111** [ztellman/aleph#137]
I was running a simple example from the Aleph `README` and changed the url from google to jsoup
```clojure
@(d/chain (http/get "http://jsoup.org/cookbook/introduction/parsing-a-document")
         :body
         bs/to-string)
```
When I run this (repl or in a main function) it blocks forever.  The same thing happened with
```clojure
@(d/chain (http/get "http://en.wikipedia.org/wiki/International_Olympic_Committee")
         :body
         bs/to-string)
```
but google works.  I have no idea what is going on and how to debug?

**Comment by ztellman** [comment]
This is because `bs/to-string` is a blocking operation, and in this case is blocking the thread which would pull down the rest of the request.  Doing the `to-string` call outside of the chain after it's been dereferenced will fix this, as will doing it like this:

```clj
@(d/chain (http/get "http://jsoup.org/cookbook/introduction/parsing-a-document")
         :body
         #(d/future (bs/to-string %)))
```

However, this is a really ugly leakage of the execution model, which you shouldn't have to work around.  There are a few ways I can fix this, I'm going to leave this issue open until I figure out the right one.  Sorry for the trouble, and thank you for the report.

**Comment by ztellman** [comment]
Your original code should work as expected now.

**Comment by shmish111** [comment]
Working perfectly, thanks for the quick fix.
