### ISSUE TITLE
HTTP Client

### ISSUE THREAD

**Issue by podviaznikov** [ztellman/aleph#163]
Thanks for great Clojure/West talk and unsession. I think I understand now why I'd want to use aleph as server.
Can you explain why I'd want to use HTTP client instead of `clj-http`? This is not that clear to me now.

Also does aleph support all the same properties as `clj-http`, e.x. `proxy-host` and `proxy-port`?

**Comment by ztellman** [comment]
You'd want to use it if you're doing lots of concurrent HTTP requests, and especially if you're acting as a proxy between the client and some other server.  This is both because you get more visibility into the behavior of the connection pool, and because each request is going to be a bit cheaper than `clj-http`.

The goal is to have parity with `clj-http`, but there are some missing features in the `0.4.0` release, including multipart bodies and the proxy functionality.

**Comment by podviaznikov** [comment]
Thanks, it's clear now. It'd nice to put this sentence into the readme.
