### ISSUE TITLE
Proxy support for http client

### ISSUE THREAD

**Issue by martinraison** [ztellman/aleph#182]
I've seen it mentioned somewhere but there didn't seem to be an issue open for it.

As a workaround for anyone looking for a solution, it might be possible to use the `pipeline-transform` argument along with `io.netty.handler.proxy.{HttpProxyHandler,Socks4ProxyHandler,Socks5ProxyHandler}`. I haven't got the time to actually try it, though.

**Comment by ztellman** [comment]
`:pipeline-transform` works on the connection, so it can't be a per-request setting, it would have to be per-connection pool.  Other than that, though, that seems like a perfectly good workaround.  I haven't had to mess around with proxies much in the past, so I'd be happy to look at any code samples you may have.

**Comment by martinraison** [comment]
If I get around to trying it I'll be glad to share.

**Comment by neverfox** [comment]
Is there anything particular that makes per-request proxy support difficult to implement in Aleph or is it just a to-do?

**Comment by ztellman** [comment]
I haven't looked at it, but I'm pretty sure it's straightforward.  I just haven't gotten to it yet.

**Comment by blandinw** [comment]
This is the `:pipeline-transform` workaround mentioned above:
```
(def my-pool (aleph.http/connection-pool
               {:connection-options
                {:pipeline-transform
                 (fn [^ChannelPipeline x]
                   (doto x
                     (.addFirst (into-array ChannelHandler [(HttpProxyHandler. (InetSocketAddress. "myproxy" 8080))]))))}}))
(deref (aleph.http/get "https://github.com" {:pool my-pool}))
```

**Comment by Atsman** [comment]
@blandinw, have it work for you? Because i just tried, and it doesn't work :(

**Comment by kachayev** [comment]
It doesn't work for me as well. At least because of this: https://github.com/ztellman/aleph/blob/a69e066600e0e3961c4b41ac4c8b4bef8edb38d5/src/aleph/netty.clj#L723-L725 - when using http proxy you need to connect to a proxy server address, not your `remote-address`. As far as I see/understand `HttpProxyHandler` does not handle a connection flow, but you can do this passing your own handler:

```clojure
(defn add-proxy [^ChannelPipeline x]
  (doto x
     (.addFirst "proxy" (aleph.netty/channel-handler
                         :connect
                         ([_ ctx _ _ promise]
                          ;; this will connect you to the proxy first and handle req/response cycle
                          ;; as usual after that
                          (.connect ctx (InetSocketAddress. "myproxy" 8080) promise))))))

(def pool (aleph.http/connection-pool
               {:connection-options
                {:pipeline-transform add-proxy}))

(deref (aleph.http/get "https://github.com" {:pool pool}))
```

Tho' there're a few things that you need to handle working with different types of proxies, like `HTTP CONNECT` (when necessary), authorization, custom headers, `Proxy-*` headers in requests etc. I'll probably prepare a pull request to cover this functionality (or at least a reasonable way to reuse proxy handlers from Netty). 

/cc @Atsman @ztellman

**Comment by kachayev** [comment]
Hm, a few observations after some reading for the `HttpProxyHandler` code:

* Handler covers HTTP tunneling proxies only, always sending HTTP CONNECT to the proxy (which might now be supported by the proxy server we're talking to). `curl` for example uses `--proxytunnel` flag to switch this ON (defaults to OFF)

* Initial message does not set `Keep-Alive` header, meaning the proxy server is free to close connection right away (obviously not the way we want to deal with proxies). 

The first one is actually a missing feature, but the second seems to be the Netty's bug. Both might be resolved by implementing own proxy handlers using `channel-handler` or subclassing `io.netty.handler.proxy.*` classes to override appropriate functionality. @ztellman what do you think? 

I also will dig deeper to try to find any open issues for the problems mentioned in Netty's repo or otherwise will do pull request into `handler-proxy` package (but the release there will obviously take some time in any case).

**Comment by kachayev** [comment]
Closing, covered here https://github.com/ztellman/aleph/commit/60fcdfd9d2c53d9a2e9e2e374551ede6e7d12c74
