### ISSUE TITLE
how do i use aleph with boot-clj?

### ISSUE THREAD

**Issue by pvinis** [ztellman/aleph#278]
i cannot make a task with start-server in there..
i have this

```

(defn handler [req]
  {:status 200
   :headers {"content-type" "text/plain"}
   :body "hello!"})

(deftask dev
  "Develop this app"
  []
  (comp
   (start-server
     handler
     {:port 3000})))
```

and i get `aleph.netty$start_server$reify__5742 cannot be cast to clojure.lang.IFn` when i run it.

**Comment by jjl** [comment]
Not aleph here, but clojure: comp takes functions as arguments and you are passing it the result of calling a function. You could actually replace the body of the task with:
```
(start-server ...)
identity)
```

**Comment by ztellman** [comment]
I'm sorry for the slow reply on this.  `start-server` doesn't return a function, it returns an object representing the server.  I'm not familiar enough with Boot to guess what you want that function to do.  Can you elaborate?

**Comment by jjl** [comment]
Boot does a strange thing somewhere between ring middleware and transducers. Lines in a deftask up until the last are just executed for side effects and the last thing returned is the task. So to have start-server as a side effect on an otherwise nil task, you can just call it and then return identity as the task.
