### ISSUE TITLE
Calling start-server lets the main thread exit

### ISSUE THREAD

**Issue by prismofeverything** [ztellman/aleph#308]
Here is the following just-trying-to-get-the-simplest-thing-to-work attempt I have now:

```clj
(ns ophion.aleph
  (:require
   [aleph.http :as http]))

(defn ophion-static
  [request]
  {:status 200
   :body "ophion"})

(defn start
  []
  (http/start-server #'ophion-static {:port 4443}))

(defn -main
  []
  (start))
```

If I run this with `lein run` for instance (setting this namespace as the :main in `project.clj`) it logs all the netty startup but then exits immediately. I was sort of hoping it would stick around.

It works if I just call start from a repl, I assume because the repl process is still running which gives the server the ability to live long enough to serve a request.

Something I can configure perhaps? I can't find anything about it in the documentation, it all seems to assume the server keeps running when you call `start-server`. 

Any ideas? Thanks!

**Comment by xsc** [comment]
Check out #238. Basically, you can use [`aleph.netty/wait-for-close`](https://github.com/ztellman/aleph/blob/master/src/aleph/netty.clj#L664) to block the main thread until the server shuts down.

@ztellman I think this needs to be addressed, either by changing the implementation or by making it very clear in the documentation. Questions about this topic keep popping up.

I don't think the current behaviour is very intuitiv, only makes it harder to use aleph:

- I need two different startup functions, one for the REPL and one for the Uberjar, since I don't want to block the REPL,
- If I'm using an aleph server within a more complex context, e.g. a [component](https://github.com/stuartsierra/component) system, I need to extract the server from some nested map and call `wait-for-close` on it. I can only do this after the whole system is started and I need to know where the server is – both are things that add unnecessary complexity.
- Most of my aleph components now have a single, pointless, non-daemon keep-alive thread next to the server, so at least the knowledge of this detail is contained within the component.

Not very constructive, I know. And I'm sorry for that. But the whole daemon-thing, esp. for the main event loops, just seems like a workaround for a deeper lying issue (see #227).

**Comment by prismofeverything** [comment]
Ah I see, so it is supposed to be an option. In that case I have seen similar things in other libraries be another option to pass in to `start-server` along with the port, something like `:daemon? true`or something.

That said, a strong assumption of a server (at least in my mind) is that it stays running forever. Actually, assumption may be too strong a word. More like a hope. Either way, maybe the non-daemon version could be called simply `start` or something, if you are using it for composition purposes, so that the thing you call `server` can run forever.

Clearly though this has probably already been thought through and you have some specific definition of the word `server` in mind. Consider it a first impression from a newb then, which has value only if you are trying to make it newb friendly.

**Comment by ztellman** [comment]
I agree that the current state of affairs isn't great.  I turned off daemonized threads not because of #227, but because worker threads didn't seem like a good fit for that property: idle worker threads are not a good reason to keep a process running.

Arguably, though, the "master" thread for servers which accepts connections *is* a good fit for that property.  I can see two ways to approach this: make that one thread daemonized, or simply add a `:wait-for-close?` property to `start-server` which is true by default.  I assume, though, that making `start-server` block would screw up most people's component-esque setups.

@xsc any strong feelings on this?

**Comment by xsc** [comment]
@ztellman I'd definitely prefer having one non-daemon thread.

**Comment by ztellman** [comment]
Okay, this is the behavior in `0.4.4-alpha3`, let me know if you encounter any issues.
