### ISSUE TITLE
Trying to understand the chat example with backpressure

### ISSUE THREAD

**Issue by doffltmiw** [ztellman/aleph#342]
[Everything Will Flow](https://youtu.be/1bNOO3xxMc0?t=31m26s), Zach presented at Cojure/West 2015, talks about a chat server, where if someone in the chat room is slow to receive a message, that would slow down everybody because publishing has to go to everyone, so we need a buffer and timout mechanism. But in my testing, I'm not seeing any slow down even without any buffer or timeout.

```clojure
(ns hello.core
  (:require
   [aleph.http :as http]
   [manifold.stream :as s]
   [manifold.deferred :as d]
   [manifold.bus :as bus]))

(def chatrooms (bus/event-bus))

(defn chat-handler
  [req]
  (d/let-flow [conn (http/websocket-connection req)
               room (s/take! conn)
               name (s/take! conn)]
    (s/connect
     (bus/subscribe chatrooms room)
     conn)

    (s/consume
     #(bus/publish! chatrooms room %)
     (->> conn
       (s/map #(str room ", " name ": " %))))))

(def s (http/start-server chat-handler {:port 10000}))

(let [conn1 @(http/websocket-client "ws://localhost:10000/")
      conn2 @(http/websocket-client "ws://localhost:10000/")]

  (s/put-all! conn1 ["shoes and ships" "Alice"])
  (s/put-all! conn2 ["shoes and ships" "Bob"])

  (s/put! conn1 "hello1")
  (s/put! conn1 "hello2")
  (s/put! conn1 "hello3")

  (println @(s/take! conn1))
  (println @(s/take! conn1))
  (println @(s/take! conn1))

  (s/close! conn1)
  (s/close! conn2)
)

(.close s)

;; Result:
;;
;;  shoes and ships, Alice: hello1
;;  shoes and ships, Alice: hello2
;;  shoes and ships, Alice: hello3
```

Q1. There's no buffer or timeout setup, but `conn1` still gets all the messages even though `conn2` doesn't take any messages.

Q2. When I evaluate the buffer several times, sometimes the order of `room` and `name` is reversed:
```
Alice, shoes and ships: hello1
Alice, shoes and ships: hello2
Alice, shoes and ships: hello3
```
Isn't `put-all!` supposed to be ordered?

Q3. Sometimes I get exceptions on closing the server:

```
SEVERE: error in deferred handler
java.util.concurrent.RejectedExecutionException: Executor is shutdown!
.....
```

This seems to be https://github.com/ztellman/aleph/issues/309. I'm on `0.4.4`, but still seeing the issue.

Q4. After several times of evaluating the buffer, the repl hangs.

**Comment by ztellman** [comment]
A1.  There is a buffer in the TCP stack, often a fairly large one, so it will take more than a few messages for `conn2` to start exerting backpressure.

A2.  I suspect this is an issue in `let-flow`, I make sure the arguments are ordered by dependency, not necessarily by the order in the let-binding.  However, if two items aren't ordered w.r.t. each other, they should reflect the order of the binding.  I'll take a look.

A3.  This generally happens when you close the server when connections are still open.  Try adding `(aleph.netty/wait-for-close s)` at the end of your buffer and see if that helps.

A4.  Can you provide a stack dump using `jstack` so I have an idea of where it's hanging?

**Comment by doffltmiw** [comment]
Adding `(aleph.netty/wait-for-close s)` helps to avoid the repl hang, but `RejectedException` still happens. I'm sure it's two websocket connections that causing the trouble, because after putting some `Thread/sleep` after closing the websocket connections, I'm no longer seeing it.

Q1. I'm able to see backpressure in action, but not when the order of `(s/take! conn)` is messed up, in that case, messages just continue to flow. I don't know what is happening. Not using `let-flow` fixes the problem, though.

```clojure
(ns hello.core
  (:require
   [aleph.http :as http]
   [manifold.stream :as s]
   [manifold.deferred :as d]
   [manifold.bus :as bus]))

(def chatrooms (bus/event-bus))

(defn chat-handler
  [req]
  (d/let-flow [conn (http/websocket-connection req)
               room (s/take! conn)
               name (s/take! conn)]
    (s/connect
     (bus/subscribe chatrooms room)
     conn)

    (s/consume
     #(bus/publish! chatrooms room %)
     (->> conn
       (s/map #(str room ", " name ": " %))))))

(def s (http/start-server chat-handler {:port 10000}))

(def received (atom 0))

(let [conn1 @(http/websocket-client "ws://localhost:10000/")
      conn2 @(http/websocket-client "ws://localhost:10000/")]

  @(s/put-all! conn1 ["shoes and ships" "Alice"])
  @(s/put-all! conn2 ["shoes and ships" "Bob"])

  (s/connect
   (s/->source (repeat "hello"))
   conn1)

  (println @(s/take! conn1))

  (s/consume
   (fn [_] (swap! received inc))
   conn1)

  (dotimes [n 10]
    (Thread/sleep 1000)
    (println "Number of messages received:" @received))

  (s/close! conn1)
  (s/close! conn2)
)

(Thread/sleep 1000)

(.close s)
(aleph.netty/wait-for-close s)
```

```
shoes and ships, Alice: hello
Number of messages received:  23678
Number of messages received:  30535
Number of messages received:  39786
Number of messages received:  42296
Number of messages received:  42296
Number of messages received:  42296
Number of messages received:  42296
Number of messages received:  42296
Number of messages received:  42296
Number of messages received:  42296
```

```
Alice, shoes and ships: hello
Number of messages received: 55291
Number of messages received: 68939
Number of messages received: 82998
Number of messages received: 96996
Number of messages received: 108911
Number of messages received: 123736
Number of messages received: 138177
Number of messages received: 150615
Number of messages received: 165391
Number of messages received: 179406
```

Q2. In the chat example of this repo, the buffer is put before publishing it to the `chatrooms`:

```clojure
(s/consume
  #(bus/publish! chatrooms room %)
  (->> conn
    (s/map #(str name ": " %))
    (s/buffer 100)))
```

but isn't it pretty redundant when there's already a write buffer in the TCP stack? Is it having an additional buffer helpful?

Q3. Is there a way to consume the data from the connection only when the bus is not paused?

Q4. This is not really a question, but the stream converted from a seq is not only drained but closed after all the items are consumed, and that led to the surprise when the `conn1` connected to it is also closed and suddenly the messages stopped to coming, without setting `:downstream?` to `false`.

```clojure
(s/connect
  (s/->source (take 20 (repeat "hello")))
  conn1)
```

It took me quite a time to figure out what's going on.

**Comment by ztellman** [comment]
A1. The two `take!` calls were running on separate threads, causing a race condition.  I've pushed a fix to Manifold to prevent this, but you can also fix it this way:

```clj
(defn chat-handler
  [req]
  (d/let-flow [conn (http/websocket-connection req)
                      [room name] [(s/take! conn) (s/take! conn)]]
    (s/connect
     (bus/subscribe chatrooms room)
     conn)

    (s/consume-async
     #(bus/publish! chatrooms room %)
     (->> conn
       (s/map #(str room ", " name ": " %))))))
```

Also notice that I've changed `consume` to `consume-async`, which actually honors the backpressure from `publish!`.  This is an API change since my 2015 talk, I apologize for any confusion there.

A2. If your buffer is significantly smaller than the existing TCP buffer, almost certainly yes.  However, if you want a larger buffer, or want to measure by a different unit than aggregate bytes across all messages, being able to specify your own buffer is useful.

A3. I'm not sure exactly what you mean by this, as the bus itself is never paused, only the subscribers it's publishing to, and the existing backpressure mechanism seems to do what you're describing.  

A4. A more idiomatic approach here would have been to use `put-all!`, as `connect` is more about coupling the lifecycle of two streams than simply conveying a fixed number of messages.
