### ISSUE TITLE
Expose ssl-session in http

### ISSUE THREAD

**Issue by mmmdreg** [ztellman/aleph#501]
I am using 2-way ssl and trying to get the client identity from the client certificate. In Netty this is done via the SSLEngine. 

I see TcpConnection in tcp.clj adds an :ssl-session key and tcp-ssl-test verifies the client identity using this, as expected. 

From the code, I think that to expose it on the http request handler, the same :ssl-session needs to be added to NettyRequest in http.core. 

Does this make sense?

In the meantime are there other workarounds to get the value without modifying aleph?

Thanks

**Comment by kachayev** [comment]
@mmmdreg You can get access to the `Channel` instance from `NettyRequest`, something like this should work:

```clojure
(-> (.get (.pipeline (.ch req)) SslHandler) .engine .getSession)
```

**Comment by mmmdreg** [comment]
Excellent thanks a lot. I will keep the issue open as it will be nice to expose it and bring it in line with tcp in any case.

**Comment by kachayev** [comment]
@mmmdreg Personally, I'm not a huge fan of exposing Java objects as values in the map. It breaks print/read loop. I would stick to just a helper function which will do pretty much the same thing I suggested with my comment. I think it covers the use case for those who need advanced functionality instead of changing things for all users.
